/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;




// ----------- << imports@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>
public abstract class Campo {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALxJrs= >>
    // ----------- >>
    private String IDcampo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALyBig= >>
    // ----------- >>
    protected String Sport;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALz0Ew= >>
    // ----------- >>
    private float Prezzo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL0Eoo= >>
    // ----------- >>
    protected int nroGiocatori;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALRqvo= >>
    // ----------- >>
    private Set<Prenotazione> ListaPrenotazioni;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALw6xI= >>
    // ----------- >>
    private Struttura StrutturaProprietaria;
    
    
    
    /*
     * costruttore di campo che non può essere richiamato se non dalle sottoclassi di Campo stesse
     */
    public Campo(float prezzo, Struttura strutturaproprietaria) {
    	this.Prezzo = prezzo;
    	ListaPrenotazioni = new HashSet<>();
    	linkStrutturaProprietaria(strutturaproprietaria);
    	setIDcampo();
    }

    
    
    /*
     * serie di metodi per restituire gli attributi fondamentali della classe
     */  
    protected String getIDcampo() {
        return IDcampo;
    }

    public String getSport() {
        return Sport;
    }

    public float getPrezzo() {
        return Prezzo;
    }

    public int getnroGiocatori() {
        return nroGiocatori;
    }

    protected Set<Prenotazione> getListaPrenotazioni() {
        return ListaPrenotazioni;
    }

    public Struttura getStrutturaProprietaria() {
        return StrutturaProprietaria;
    }

    /*
     * serie di metodi per settare singolarmente gli attributi della classe
     */ 
    protected void setIDcampo() {    	
		int n = StrutturaProprietaria.getListaCampi().size();
		this.IDcampo = "C_"+ (n+1);
    }

    protected void setStrutturaProprietaria(Struttura StrutturaProprietaria) {
        this.StrutturaProprietaria = StrutturaProprietaria;
    }

    /*
     * aggiunge una nuova prenotazione alla ListaPrenotazioni del Campo
     */
    public void linkListaPrenotazioni(Prenotazione prenotazione) {
        if (prenotazione != null) {
        	prenotazione.setCampoAssociato(this);
            getListaPrenotazioni().add(prenotazione);
        }
    }

    /*
     * serve per aggiornare la struttura proprietaria e aggiungere il campo alla sua lista
     */
    public void linkStrutturaProprietaria(Struttura _StrutturaProprietaria) {
        if (_StrutturaProprietaria != null) {
            _StrutturaProprietaria.getListaCampi().add(this);
        }
        //aggiorno la StrutturaProprietaria per il campo
        setStrutturaProprietaria(_StrutturaProprietaria);
    }
    
    /*
     * serve per togliere una prenotazione dalla ListaPrenotazioni e togliere alla prenotazione questo campo
     */
    public void unlinkListaPrenotazioni(Prenotazione prenotazione) {
        if (prenotazione != null) {
        	prenotazione.setCampoAssociato(null);
            getListaPrenotazioni().remove(prenotazione);
        }
    }
// ----------- << class.extras@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>
}