/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>
public class CampoBasket extends Campo {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyAMEkKE= >>
    // ----------- >>
    private float altezzaCanestro;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAMFK/M= >>
    // ----------- >>
    private int nroGiocatori;
    
    /*
     * costruttore CampoBasket
     */
    public CampoBasket() {
    	
    }

    public float getAltezzaCanestro() {
        return altezzaCanestro;
    }

    public int getNroGiocatori() {
        return nroGiocatori;
    }

// ----------- << class.extras@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>
}