/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyAL9hF4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyAL9hF4= >>
// ----------- >>
public class CampoCalcetto extends Campo {

	// ----------- << attribute.annotations@AAAAAAF+h+SsyAL/8Ls= >>
    // ----------- >>
    private String tipoTerreno;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAMAKCU= >>
    // ----------- >>
    private boolean campoCoperto;

    
    
    /*
     * costruttore CampoCalcetto
     */
    public CampoCalcetto(float prezzo, Struttura strutturaproprietaria,String terreno, boolean campoCoperto) {
		super(prezzo, strutturaproprietaria);
		// TODO Auto-generated constructor stub
		Sport="Calcetto";
		nroGiocatori=10;
		tipoTerreno=terreno;
		this.campoCoperto=campoCoperto;
	}
    

    public String getTipoTerreno() {
        return tipoTerreno;
    }

    public boolean isCampoCoperto() {
        return campoCoperto;
    }

    public int getNroGiocatori() {
        return nroGiocatori;
    }

// ----------- << class.extras@AAAAAAF+h+SsyAL9hF4= >>
// ----------- >>
}