/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>
public class CampoBasket extends Campo {
	
	// ----------- << attribute.annotations@AAAAAAF+h+SsyAMEkKE= >>
    // ----------- >>
    private double altezzaCanestro;
    
    
    /*
     * costruttore CampoBasket
     */
    public CampoBasket(float prezzo,  Struttura strutturaproprietaria) {
		super(prezzo, strutturaproprietaria);
		// TODO Auto-generated constructor stub
		Sport="Basket";
		nroGiocatori=10;
		altezzaCanestro=3.05;
	}

    public double getAltezzaCanestro() {
        return altezzaCanestro;
    }

    public int getNroGiocatori() {
        return nroGiocatori;
    }

    public void setAltezzaCanestro(double h) {
    	altezzaCanestro=h;
    }
// ----------- << class.extras@AAAAAAF+h+SsyAMCvEA= >>
// ----------- >>
}