/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>
public abstract class Campo {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALxJrs= >>
    // ----------- >>
    private String IDcampo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALyBig= >>
    // ----------- >>
    private String Sport;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALz0Ew= >>
    // ----------- >>
    private float Prezzo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL0Eoo= >>
    // ----------- >>
    private int nroMaxPersone;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALRqvo= >>
    // ----------- >>
    private Set<Prenotazione>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALw6xI= >>
    // ----------- >>
    private Struttura ;

    private String getIDcampo() {
        return IDcampo;
    }

    public String getSport() {
        return Sport;
    }

    public float getPrezzo() {
        return Prezzo;
    }

    public int getNroMaxPersone() {
        return nroMaxPersone;
    }

    public Set<Prenotazione> get() {
        return ;
    }

    public Struttura get() {
        return ;
    }

    private void setIDcampo(String IDcampo) {
        this.IDcampo = IDcampo;
    }

    public void setSport(String Sport) {
        this.Sport = Sport;
    }

    public void setNroMaxPersone(int nroMaxPersone) {
        this.nroMaxPersone = nroMaxPersone;
    }

    public void set(Struttura ) {
        this. = ;
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Struttura _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Prenotazione _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Prenotazione _, Iterator<Prenotazione> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyAL1hOw= >>
    // ----------- >>
    protected void aggiungiPrenotazione() {
    // ----------- << method.body@AAAAAAF+h+SsyAL1hOw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF/G83rC8T6iE4= >>
    // ----------- >>
    public void stampaPrenotazione() {
    // ----------- << method.body@AAAAAAF/G83rC8T6iE4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+h+SsyALtH+M= >>
// ----------- >>
}