/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyALA1XA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALA1XA= >>
// ----------- >>
public class Cliente {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALBPyI= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALCu5k= >>
    // ----------- >>
    private String Cognome;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALDSJM= >>
    // ----------- >>
    private String CodiceFiscale;
    
    private RegistroStrutture registro;
    
    
    public Cliente() {
		// TODO Auto-generated constructor stub
    	this.registro = RegistroStrutture.registro;
	}
    

    /*
     * serie di metodi get per ottenere gli attributi della classe
     */
    private String getNome() {
        return Nome;
    }

    private String getCognome() {
        return Cognome;
    }

    protected String getCodiceFiscale() {
        return CodiceFiscale;
    }

    /*
     * serie di metodi set per settare gli attributi della classe
     */
    private void setNome(String Nome) {
        this.Nome = Nome;
    }

    private void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

    protected void setCodiceFiscale(String CodiceFiscale) {
        this.CodiceFiscale = CodiceFiscale;
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyALEwVw= >>
    // ----------- >>
    protected void calcoloSconto() {
    // ----------- << method.body@AAAAAAF+h+SsyALEwVw= >>
    // ----------- >>
    }
    
    /**
    * @param sport 
    * @param orario 
    * @param spogliatoio 
    * @param struttura 
    * @param collettiva
    */
    // ----------- << method.annotations@AAAAAAF+h+SsyALFTmM= >>
    // ----------- >>
    protected void controlloDisponibilitaCampo(String sport, Date orario, boolean spogliatoio, Struttura struttura, boolean collettiva) {
    // ----------- << method.body@AAAAAAF+h+SsyALFTmM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+h+SsyALL5Xc= >>
    // ----------- >>
    protected void controlloDisponibilitaSpogliatoio() {
    // ----------- << method.body@AAAAAAF+h+SsyALL5Xc= >>
    // ----------- >>
    	
    }

// ----------- << class.extras@AAAAAAF+h+SsyALA1XA= >>
// ----------- >>
}