/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyALPzog= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALPzog= >>
// ----------- >>
public class Prenotazione {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALaojI= >>
    // ----------- >>
    private Date DataOra;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALb16k= >>
    // ----------- >>
    private String CodicePrenotazione;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALcE08= >>
    // ----------- >>
    private String Sport;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALdHSo= >>
    // ----------- >>
    private boolean Spogliatoio;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALe6QE= >>
    // ----------- >>
    private float Prezzo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALf/Ck= >>
    // ----------- >>
    private Campo NomeCampo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALgkOA= >>
    // ----------- >>
    private Spogliatoio NomeSpogliatoio;

    // ----------- << attribute.annotations@AAAAAAF/G//c6YdTHV0= >>
    // ----------- >>
    private String CodiceFiscalePrenotante;

    // ----------- << attribute.annotations@AAAAAAF/HAijB6u3ZZU= >>
    // ----------- >>
    private Struttura NomeStruttura;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALS8Ac= >>
    // ----------- >>
    private Campo ;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALVPUU= >>
    // ----------- >>
    private Spogliatoio ;

    public Date getDataOra() {
        return DataOra;
    }

    protected String getCodicePrenotazione() {
        return CodicePrenotazione;
    }

    public String getSport() {
        return Sport;
    }

    public boolean isSpogliatoio() {
        return Spogliatoio;
    }

    public float getPrezzo() {
        return Prezzo;
    }

    public Campo getNomeCampo() {
        return NomeCampo;
    }

    public Spogliatoio getNomeSpogliatoio() {
        return NomeSpogliatoio;
    }

    public String getCodiceFiscalePrenotante() {
        return CodiceFiscalePrenotante;
    }

    public Struttura getNomeStruttura() {
        return NomeStruttura;
    }

    public Campo get() {
        return ;
    }

    public Spogliatoio get() {
        return ;
    }

    public void setDataOra(Date DataOra) {
        this.DataOra = DataOra;
    }

    protected void setCodicePrenotazione(String CodicePrenotazione) {
        this.CodicePrenotazione = CodicePrenotazione;
    }

    public void setSport(String Sport) {
        this.Sport = Sport;
    }

    public void setSpogliatoio(boolean Spogliatoio) {
        this.Spogliatoio = Spogliatoio;
    }

    public void setPrezzo(float Prezzo) {
        this.Prezzo = Prezzo;
    }

    public void setNomeCampo(Campo NomeCampo) {
        this.NomeCampo = NomeCampo;
    }

    public void setNomeSpogliatoio(Spogliatoio NomeSpogliatoio) {
        this.NomeSpogliatoio = NomeSpogliatoio;
    }

    public void setCodiceFiscalePrenotante(String CodiceFiscalePrenotante) {
        this.CodiceFiscalePrenotante = CodiceFiscalePrenotante;
    }

    public void setNomeStruttura(Struttura NomeStruttura) {
        this.NomeStruttura = NomeStruttura;
    }

    public void set(Campo ) {
        this. = ;
    }

    public void set(Spogliatoio ) {
        this. = ;
    }

    public void link(Campo _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Spogliatoio _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyALhZdw= >>
    // ----------- >>
    protected void calcolaPrezzo() {
    // ----------- << method.body@AAAAAAF+h+SsyALhZdw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+h+SsyALPzog= >>
// ----------- >>
}