/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.util.Map.*;
import java.time.*;


// ----------- << imports@AAAAAAF+h+SsyALPzog= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALPzog= >>
// ----------- >>
public class Prenotazione {
	public static int contPrenotazioni=0;
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALaojI= >>
    // ----------- >>
    private Date DataOra;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALb16k= >>
    // ----------- >>
    private String CodicePrenotazione;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALcE08= >>
    // ----------- >>
    private String Sport;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALdHSo= >>
    // ----------- >>
    private boolean Spogliatoio;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALe6QE= >>
    // ----------- >>
    private float Prezzo;

    // ----------- << attribute.annotations@AAAAAAF/G//c6YdTHV0= >>
    // ----------- >>
    private String CodiceFiscalePrenotante;

    // ----------- << attribute.annotations@AAAAAAF/HAijB6u3ZZU= >>
    // ----------- >>
    private Struttura NomeStruttura;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALS8Ac= >>
    // ----------- >>
    private Campo CampoAssociato;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALVPUU= >>
    // ----------- >>
    private Spogliatoio SpogliatoioAssociato;

   
    
    /*
     * costrutture della classe
     */
    public Prenotazione(Date data, String sport, boolean docce, String cf, Struttura struttura, Campo campo, Spogliatoio spogliatoio ) {
		// TODO Auto-generated constructor stub
    	DataOra=data;
    	Sport=sport;
    	Spogliatoio=docce;
    	CodiceFiscalePrenotante=cf;
    	NomeStruttura=struttura;
    	linkCampoAssociato(campo);
    	linkSpogliatoioAssociato(spogliatoio);
    	
	}
    
    /*
     * serie di get per ottenere gli attributi della classe
     */
    public Date getDataOra() {
        return DataOra;
    }

    protected String getCodicePrenotazione() {
        return CodicePrenotazione;
    }

    public String getSport() {
        return Sport;
    }

    public boolean isSpogliatoio() {
        return Spogliatoio;
    }

    public float getPrezzo() {
        return Prezzo;
    }

    public String getCodiceFiscalePrenotante() {
        return CodiceFiscalePrenotante;
    }

    public Struttura getNomeStruttura() {
        return NomeStruttura;
    }

    public Campo getCampoAssociato() {
        return CampoAssociato;
    }

    public Spogliatoio getSpogliatoioAssociato() {
        return SpogliatoioAssociato;
    }

    /*
     * serie di set per settare gli attributi della classe
     */
    public void setDataOra(Date DataOra) {
        this.DataOra = DataOra;
    }

    
    protected void setCodicePrenotazione() {
    	contPrenotazioni+=1;
        CodicePrenotazione ="P_"+contPrenotazioni;
    }

    public void setSport(String Sport) {
        this.Sport = Sport;
    }

    public void setSpogliatoio(boolean Spogliatoio) {
        this.Spogliatoio = Spogliatoio;
    }

    public void setCodiceFiscalePrenotante(String CodiceFiscalePrenotante) {
        this.CodiceFiscalePrenotante = CodiceFiscalePrenotante;
    }

    public void setNomeStruttura(Struttura NomeStruttura) {
        this.NomeStruttura = NomeStruttura;
    }

    public void setCampoAssociato(Campo CampoAssociato) {
        this.CampoAssociato = CampoAssociato;
    }

    public void setSpogliatoioAssociato(Spogliatoio SpogliatoioAssociato) {
        this.SpogliatoioAssociato = SpogliatoioAssociato;
    }

    /*
     * metodo per cambiare il campo associato a questa prenotazione e per aggiungere al campo questa prenotazione nella sua lista
     */
    public void linkCampoAssociato(Campo campoAssociato) {
        if (campoAssociato != null) {
            campoAssociato.getListaPrenotazioni().add(this);
        }

        setCampoAssociato(campoAssociato);
    }

    /*
     * metodo per cambiare lo spogliatoio associato a questa prenotazione e per aggiungere allo spogliatoio questa prenotazione nella sua lista
     */
    public void linkSpogliatoioAssociato(Spogliatoio spogliatoioAssociato) {
        if (spogliatoioAssociato != null) {
            spogliatoioAssociato.getListaPrenotazioni().add(this);
        }

        unlinkSpogliatoioAssociato();
        setSpogliatoioAssociato(spogliatoioAssociato);
    }


    /*
     * metodo per togliere lo spogliatoio alla prenotazione e togliere anche allo spogliatoio questa prenotazione dalla sua lista
     */
    public void unlinkSpogliatoioAssociato() {
        if (getSpogliatoioAssociato() != null) {
            getSpogliatoioAssociato().getListaPrenotazioni().remove(this);
            setSpogliatoioAssociato(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyALhZdw= >>
    // ----------- >>
    protected void calcolaPrezzo() {
    // ----------- << method.body@AAAAAAF+h+SsyALhZdw= >>
    	float costoPrenotazione=CampoAssociato.getPrezzo();
    	
    	if(Spogliatoio) {
    		costoPrenotazione+=SpogliatoioAssociato.getPrezzo();
    	}
    	
    	Map<String,Integer> lista = NomeStruttura.getConteggioPrenotazioni();
    	Iterator<Entry<String,Integer>> it= lista.entrySet().iterator();
    	
    	while(it.hasNext()) {
    		Map.Entry<String,Integer> set= (Map.Entry<String,Integer>) it.next();
    		if(set.getKey()==CodiceFiscalePrenotante && set.getValue()>=5) {
    			costoPrenotazione*=0.8;//sconto 20 %
    			return;
    		}
    	}
    	
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+h+SsyALPzog= >>
// ----------- >>
}