/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+i5Bd8z8/cWo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+i5Bd8z8/cWo= >>
// ----------- >>
public class RegistroStrutture {
    // ----------- << attribute.annotations@AAAAAAF/Ih9yqcv7c7Q= >>
    // ----------- >>
    private Set<Struttura>  = new HashSet<>();

    public Set<Struttura> get() {
        return ;
    }

    public void link(Struttura _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void unlink(Struttura _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Struttura> it) {
        it.remove();
    }

    // ----------- << method.annotations@AAAAAAF/Ae3NRlS2ang= >>
    // ----------- >>
    protected void check() {
    // ----------- << method.body@AAAAAAF/Ae3NRlS2ang= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+i5Bd8z8/cWo= >>
// ----------- >>
}