/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyAL28Vw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyAL28Vw= >>
// ----------- >>
public class Spogliatoio {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL6TAM= >>
    // ----------- >>
    private int Numero;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL7r2A= >>
    // ----------- >>
    private float Prezzo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALURH0= >>
    // ----------- >>
    private Set<Prenotazione>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL5VLU= >>
    // ----------- >>
    private Struttura ;

    public int getNumero() {
        return Numero;
    }

    public float getPrezzo() {
        return Prezzo;
    }

    public Set<Prenotazione> get() {
        return ;
    }

    public Struttura get() {
        return ;
    }

    public void setNumero(int Numero) {
        this.Numero = Numero;
    }

    public void set(Struttura ) {
        this. = ;
    }

    public void link(Prenotazione _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Struttura _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Prenotazione _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Prenotazione _, Iterator<Prenotazione> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyAL8Se0= >>
    // ----------- >>
    protected void aggiungiPrenotazione() {
    // ----------- << method.body@AAAAAAF+h+SsyAL8Se0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF/G81mDMH+nV0= >>
    // ----------- >>
    public void stampaPrenotazione() {
    // ----------- << method.body@AAAAAAF/G81mDMH+nV0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+h+SsyAL28Vw= >>
// ----------- >>
}