/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package piattaforma;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+h+SsyALiE3I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+h+SsyALiE3I= >>
// ----------- >>
public class Struttura {
    // ----------- << attribute.annotations@AAAAAAF+h+SsyALmvyA= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALnspQ= >>
    // ----------- >>
    private String Indirizzo;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALo/5s= >>
    // ----------- >>
    private String Citta;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALp7xQ= >>
    // ----------- >>
    private String IDstruttura;

    // ----------- << attribute.annotations@AAAAAAF/G/HPwGbFGOw= >>
    // ----------- >>
    private void ConteggioPrenotazioni;

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALlXF8= >>
    // ----------- >>
    private Set<Cliente>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+h+SsyALvLyc= >>
    // ----------- >>
    private Set<Campo>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF+h+SsyAL4npc= >>
    // ----------- >>
    private Set<Spogliatoio>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public String getIndirizzo() {
        return Indirizzo;
    }

    public String getCitta() {
        return Citta;
    }

    private String getIDstruttura() {
        return IDstruttura;
    }

    private void getConteggioPrenotazioni() {
        return ConteggioPrenotazioni;
    }

    public Set<Cliente> get() {
        return ;
    }

    public Set<Campo> get() {
        return ;
    }

    public Set<Spogliatoio> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setIndirizzo(String Indirizzo) {
        this.Indirizzo = Indirizzo;
    }

    public void setCitta(String Citta) {
        this.Citta = Citta;
    }

    private void setIDstruttura(String IDstruttura) {
        this.IDstruttura = IDstruttura;
    }

    private void setConteggioPrenotazioni(void ConteggioPrenotazioni) {
        this.ConteggioPrenotazioni = ConteggioPrenotazioni;
    }

    public void link(Cliente _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(Campo _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Spogliatoio _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Cliente _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Cliente> it) {
        it.remove();
    }

    public void unlink(Campo _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Campo _, Iterator<Campo> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Spogliatoio _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Spogliatoio _, Iterator<Spogliatoio> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAF+h+SsyALqHG8= >>
    // ----------- >>
    protected void aggiungiBan() {
    // ----------- << method.body@AAAAAAF+h+SsyALqHG8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+h+SsyALrFSc= >>
    // ----------- >>
    protected void aggiungiCampo() {
    // ----------- << method.body@AAAAAAF+h+SsyALrFSc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+h+SsyALsdgk= >>
    // ----------- >>
    protected void aggiungiSpogliatoio() {
    // ----------- << method.body@AAAAAAF+h+SsyALsdgk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF/AeFs0EnWX1E= >>
    // ----------- >>
    public void stampaPrenotazioni() {
    // ----------- << method.body@AAAAAAF/AeFs0EnWX1E= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF/Aept5Ez0NzU= >>
    // ----------- >>
    protected void controllaBan() {
    // ----------- << method.body@AAAAAAF/Aept5Ez0NzU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF/G/L4AWjwnek= >>
    // ----------- >>
    protected void aggiornaConteggioPrenotazioni() {
    // ----------- << method.body@AAAAAAF/G/L4AWjwnek= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF+h+SsyALiE3I= >>
// ----------- >>
}